# Convert the header file generated by the Python package "rasterio" to the ENVI header format

def rasterio2ENVIhdr(file_path,hdr_band_names,hdr_wavelength,hdr_wavelength_units,is_Mask = False):

# file_path: the path to the header file
# hdr_band_names: a string which will be written directly to the output header file containing band names. The official format should be "band names = {B02,B03,B04,B05,B06,B07,B08,B8A,B11,B12}"
# hdr_wavelength: a string which will be written directly to the output header file containing wavelength. The official format should be "wavelength = {496.6,560,664.5,703.9,740.2,782.5,835.1,864.8,1613.7,2202.4}"
# hdr_wavelength_units: a string which will be written directly to the output header file containing wavelength unit. The official format should be "wavelength units = nanometers"
# is_Mask: set to True only if the input header file is associated with a mask raster layer, hence only containing 1 band

    line_index_read = 0
    line_index_write = 0
    lines = ''
    with open(file_path, 'r') as file:
        lines = file.readlines()
        for line in lines:
            line_index_read += 1
            if 'band names' in line:
                break
    print('Lines after the row ' + str(line_index_read) + ' will be deleted!')
    with open(file_path, 'w') as file:
        for line in lines:
            line_index_write += 1
            if line_index_write < line_index_read:
                file.write(line)
    with open(file_path, 'a') as file:
        if is_Mask:
            file.write('band names = {Band 1}')
            file.write('\n')
        else:
            file.write(hdr_band_names)
            file.write('\n')
            file.write(hdr_wavelength)
            file.write('\n')
            file.write(hdr_wavelength_units)